# Generated by Django 6.0.6 on 2026-06-30 09:17
#
# Hand-edited after autogeneration: the `organization` FK is added nullable,
# backfilled, then made non-null, so this migration is safe on populated DBs
# (no hardcoded `default=1`). Definitions take their organization from the
# org-bearing path through their flavours (flavour -> release -> app ->
# organization); the other registries have no deterministic path, so any
# pre-existing rows fall back to the first organization. On empty tables (the
# normal case) the backfill is a no-op.

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization(apps, schema_editor):
    Organization = apps.get_model("authentikate", "Organization")
    Definition = apps.get_model("bridge", "Definition")
    Collection = apps.get_model("bridge", "Collection")
    Protocol = apps.get_model("bridge", "Protocol")
    StateDefinition = apps.get_model("bridge", "StateDefinition")

    fallback = Organization.objects.order_by("id").first()

    for definition in Definition.objects.all():
        flavour = definition.flavours.select_related("release__app__organization").first()
        org = flavour.release.app.organization if flavour else fallback
        if org is None:
            raise RuntimeError(
                "Cannot backfill Definition.organization: no related flavour and no "
                "organization exists. Create an organization or clear the table first."
            )
        definition.organization = org
        definition.save(update_fields=["organization"])

    for model in (Collection, Protocol, StateDefinition):
        rows = model.objects.all()
        if rows.exists() and fallback is None:
            raise RuntimeError(
                f"Cannot backfill {model.__name__}.organization: rows exist but no "
                "organization exists. Create an organization or clear the table first."
            )
        rows.update(organization=fallback)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='definition',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='statedefinition',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_definitions', to='authentikate.organization'),
        ),
        migrations.RunPython(backfill_organization, noop_reverse),
        migrations.AlterField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='authentikate.organization'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='authentikate.organization'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='authentikate.organization'),
        ),
        migrations.AlterField(
            model_name='statedefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_definitions', to='authentikate.organization'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text='The name of this Collection', max_length=1000),
        ),
        migrations.AlterField(
            model_name='definition',
            name='hash',
            field=models.CharField(help_text='The hash of the Action (unique within an organization)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(help_text='The name of this Protocol', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='Unique collection for org'),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('hash', 'organization'), name='Unique definition for org'),
        ),
        migrations.AddConstraint(
            model_name='protocol',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='Unique protocol for org'),
        ),
    ]
