# Generated by Django 5.2 on 2026-04-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(help_text='The cleartext name of this State', max_length=1000)),
                ('description', models.TextField(help_text='A description for the State')),
                ('meta', models.JSONField(blank=True, help_text='Meta data about this State', null=True)),
                ('interfaces', models.JSONField(default=list, help_text='Intercae that we use to interpret the meta data')),
                ('ports', models.JSONField(default=list, help_text='Inputs for this Action')),
                ('protocols', models.ManyToManyField(blank=True, help_text='The protocols this State implements (e.g. Predicate)', related_name='states', to='bridge.protocol')),
            ],
        ),
    ]
