# Generated by Django 5.2 on 2025-08-02 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='When this release was created'),
        ),
        migrations.AddField(
            model_name='release',
            name='released_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this release was created'),
            preserve_default=False,
        ),
    ]
