# Generated by Django 4.2.9 on 2024-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flavour",
            name="build_id",
        ),
    ]
