# Generated by Django 4.2.9 on 2024-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0002_remove_flavour_build_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="api_token",
        ),
        migrations.AddField(
            model_name="deployment",
            name="secret_params",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deployment",
            name="untyped_params",
            field=models.JSONField(default=dict),
        ),
    ]
