# Generated by Django 5.2 on 2025-08-14 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_release_created_at_release_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
