# Generated by Django 5.2 on 2025-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_githubrepo_added_at_githubrepo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='vetted',
            field=models.BooleanField(default=False),
        ),
    ]
