# Generated by Django 6.0.6 on 2026-08-20 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('bridge', '0003_dedupe_repo_and_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='status',
            field=models.CharField(default='PENDING', max_length=1000),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='bridge.repo'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('identifier', 'organization'), name='Unique app for org'),
        ),
        migrations.AddConstraint(
            model_name='githubrepo',
            constraint=models.UniqueConstraint(fields=('repo', 'user', 'branch', 'organization'), name='Unique repo for url'),
        ),
    ]
