# Generated by Django 4.2.9 on 2024-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bridge",
            "0003_remove_deployment_api_token_deployment_secret_params_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="local_id",
            field=models.CharField(default="unset", max_length=2000),
        ),
    ]
