# Generated by Django 4.2.9 on 2024-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0003_alter_backend_kind_alter_repo_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="pod",
            name="client_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="pod",
            name="backend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pods",
                to="bridge.backend",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.CharField(max_length=1000)),
                ("name", models.CharField(default="unset", max_length=1000)),
                ("qualifiers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="bridge.backend",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pod",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pods",
                to="bridge.resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("backend", "resource_id"), name="Unique resource for backend "
            ),
        ),
    ]
