# Generated by Django 4.2.9 on 2024-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0003_setup_delete_installedrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="setup",
            name="command",
            field=models.CharField(default="arkitekt run prod", max_length=400),
        ),
        migrations.AddField(
            model_name="setup",
            name="instance",
            field=models.CharField(default="default", max_length=400),
        ),
    ]
