# Generated by Django 4.2.9 on 2024-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0004_deployment_local_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavour",
            name="manifest",
            field=models.JSONField(default=dict),
        ),
    ]
