# Generated by Django 4.2.9 on 2024-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0004_pod_client_id_alter_pod_backend_resource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="qualifiers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
