# Generated by Django 4.2.9 on 2024-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0004_setup_command_setup_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="setup",
            name="fakts_url",
            field=models.CharField(default="lok:80", max_length=400),
        ),
    ]
