# Generated by Django 4.2.9 on 2024-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0005_flavour_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavour",
            name="requirements",
            field=models.JSONField(default=dict),
        ),
    ]
