# Generated by Django 4.2.9 on 2024-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0006_pod_delete_whale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pod",
            name="creator",
        ),
    ]
