# Generated by Django 6.0.6 on 2026-09-22 08:32

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('bridge', '0007_definition_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='embedding_model',
            field=models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200),
        ),
        migrations.AddField(
            model_name='flavour',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True),
        ),
        migrations.AddField(
            model_name='flavour',
            name='embedding_model',
            field=models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200),
        ),
        migrations.AddField(
            model_name='repo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='embedding_model',
            field=models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['embedding_model'], name='app_emb_model_idx'),
        ),
        migrations.AddIndex(
            model_name='flavour',
            index=models.Index(fields=['embedding_model'], name='flavour_emb_model_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['embedding_model'], name='repo_emb_model_idx'),
        ),
    ]
