# Generated by Django 4.2.9 on 2024-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0008_collection_protocol_remove_flavour_definitions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="flavous",
            field=models.ManyToManyField(
                help_text="The flavours this Definition belongs to",
                related_name="definitions",
                to="bridge.flavour",
            ),
        ),
    ]
