# Generated by Django 6.0.6 on 2026-09-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('bridge', '0008_app_embedding_app_embedding_model_flavour_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_id', models.CharField(help_text='The lok mandate that lets the agent provision this release as the approver.', max_length=1000)),
                ('agent', models.CharField(help_text='Identifier of the agent app (deployer) the mandate names.', max_length=1000)),
                ('digest', models.CharField(help_text='The release digest at approval time (see bridge.approvals.release_digest).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_approvals', to=settings.AUTH_USER_MODEL)),
                ('backends', models.ManyToManyField(blank=True, help_text='Backends allowed to deploy under this approval. Empty means any backend of the organization.', related_name='approvals', to='bridge.backend')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_approvals', to='authentikate.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bridge.release')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval',
            field=models.ForeignKey(blank=True, help_text='The approval this deployment was made under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='bridge.releaseapproval'),
        ),
    ]
