# Generated by Django 6.0.6 on 2026-10-05 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("bridge", "0009_release_approvals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The imported repository this app's releases come from. Another repository claiming the identifier is refused.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apps",
                to="bridge.repo",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="channel",
            field=models.CharField(
                blank=True,
                help_text="The channel this is the latest build of. Null for a release proper, which never changes.",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="revision",
            field=models.CharField(
                blank=True,
                help_text="The source revision this was built from",
                max_length=400,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OciRepo",
            fields=[
                (
                    "repo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bridge.repo",
                    ),
                ),
                (
                    "registry",
                    models.CharField(
                        help_text="The registry host, e.g. ghcr.io", max_length=1000
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        help_text="The repository path on the registry, e.g. org/app",
                        max_length=2000,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="The channel tags followed besides the releases, e.g. ['main']",
                    ),
                ),
                (
                    "seen",
                    models.JSONField(
                        default=dict,
                        help_text="Every tag already read, with the digest it pointed at then",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the registry was last read",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_repos",
                        to="authentikate.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registry", "repository", "organization"),
                        name="Unique oci repo for org",
                    )
                ],
            },
            bases=("bridge.repo",),
        ),
    ]
