# Generated by Django 4.2.9 on 2024-01-22 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0009_definition_flavous"),
    ]

    operations = [
        migrations.RenameField(
            model_name="definition",
            old_name="flavous",
            new_name="flavours",
        ),
    ]
