"""
Django settings for mikro_server project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from .configuration import Settings
from .logs import build_logging


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.django.secret_key  # TODO: Change this in production


# SECURITY WARNING: don't run with debug turned on in production!
# Both of these were hardcoded (`True` and `["*"]`) while the typed configuration
# validated `django.debug` and `django.hosts` and then had them thrown away -- so
# CONFIG.md documented a debug flag that could not turn debug off.
DEBUG = conf.django.debug

ALLOWED_HOSTS: list[str] = conf.django.hosts


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "strawberry_django",
    "channels_redis",
    "guardian",
    "simple_history",
    "authentikate",
    "koherent",
    "kante",
    "channels",
    "django_probes",
    "datalayer",
    "bridge",
    "health_check",
    "health_check.db",
]


AUTH_USER_MODEL = "authentikate.User"


CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": conf.redis.channel_prefix},
    },
}

CORS_ALLOW_ALL_ORIGINS = True

MY_SCRIPT_NAME = conf.django.force_script_name

# Assigned twice until now -- once here and once below `ASGI_APPLICATION` -- and the
# second assignment replaced this dict wholesale. So both description flags were dead
# (which is why every field in `bridge/types.py` carries a hand-written `description=`)
# while `USE_DEPRECATED_FILTERS` was live, against a filter layer that had already been
# migrated off the deprecated form (see the module docstring of `tests/test_filters.py`).
STRAWBERRY_DJANGO = {
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
    "USE_DEPRECATED_FILTERS": True,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kabinet_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is default
    "guardian.backends.ObjectPermissionBackend",
)

WSGI_APPLICATION = "kabinet_server.wsgi.application"
ASGI_APPLICATION = "kabinet_server.asgi.application"

REPO_MAP = conf.repo_map
ENSURED_REPOS = conf.ensured_repos
DEFAULT_REPOS = conf.default_repos
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Semantic search (the vendored ``embeddings`` package). Definitions embed their name +
# description into a pgvector column on save, with a model2vec static model that runs in this
# process (no service, no GPU, ~1 ms per row). ``DefinitionFilter.search`` ORs "cosine
# distance below DISTANCE_THRESHOLD" onto its substring match. DIMENSIONS is also the width of
# the database column: the ``embeddings`` system checks refuse to start when the model, this
# setting and the column disagree. Rows filled by another model are re-embedded by an
# in-process loop (see ``kabinet_server/asgi.py``), never by a command.
EMBEDDINGS = {
    "ENABLED": conf.embeddings.enabled,
    "MODEL": conf.embeddings.model,
    "MODEL_PATH": conf.embeddings.model_path,
    "DIMENSIONS": conf.embeddings.dimensions,
    "DISTANCE_THRESHOLD": conf.embeddings.distance_threshold,
    "SWEEP_INTERVAL": conf.embeddings.sweep_interval,
    "SWEEP_BATCH_SIZE": conf.embeddings.sweep_batch_size,
}
# The in-process healer that re-embeds stale rows. Off under the test suite, which calls
# ``embeddings.healer.reembed_stale`` directly so a background pass never races an assertion.
EMBEDDINGS_HEALER_ENABLED = True


AUTHENTIKATE = conf.authentikate.model_dump()


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{conf.redis.host}:{conf.redis.port}/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "kluster_server_cache",
    }
}


CACHE_TTL_DEFAULT = 60 * 15


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Console logging: one plain line per record on root; see logs.py. ``LOG_LEVEL=DEBUG``
# (env) brings back per-event detail; ``django.enable_rich_logging`` renders with rich.
LOGGING = build_logging(
    level=os.environ.get("LOG_LEVEL", conf.django.log_level),
    rich=conf.django.enable_rich_logging,
)
